[project]
name = "pyth-delegate"
authors = ["Pyth Core Team"]
description = "Decentralized delegation and verification contract for Pyth Network"
telemetry = false
requirements = []
[contracts.pyth-delegate]
path = "contracts/pyth-delegate.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
